### ISSUE TITLE
Problem of data link

### ISSUE THREAD

**Issue by super233** [qinenergy/corda#1]
The link of [Stereo Depth Estimation for Cityscapes](https://www.qin.ee/depth/city_stereo_depth.zip) is unavailable, can you fix it?

**Comment by qinenergy** [comment]
Link fixed. Thanks for letting us know.

**Comment by qinenergy** [comment]
http://zh.qin.ee/depth/city_stereo_depth.zip

**Comment by sj-li** [comment]
Hi, it seems the link is unavailable again, could you fix it? thanks~
https://zh.qin.ee/depth/city_stereo_depth.zip

**Comment by qinenergy** [comment]
> Hi, it seems the link is unavailable again, could you fix it? thanks~
> https://zh.qin.ee/depth/city_stereo_depth.zip

Nginx was down.. Now online again. Thank you very much for letting us know.

**Comment by sj-li** [comment]
Thanks!
