### ISSUE TITLE
About intrinsics used in GTA depth estimation

### ISSUE THREAD

**Issue by Ichinose0code** [qinenergy/corda#11]
Thanks a lot for your fantastic work. When I followed your depth estimation mentioned in issue#7, I went to the https://playing-for-benchmarks.org. However,its camera calibration doesn't include intrinsic matrix directly, which is needed in Monodepth2 depth estimation. Would you kindly share the intrinsic of GTA you used in depth estimation? Or may I know a way to convert GTA's projection matrix to intrinsic matrix?

**Comment by lhoyer** [comment]
You can find the data loader, which is used for self-supervised depth estimation, here: https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/ssda/loader/gta_seq_loader.py

**Comment by Ichinose0code** [comment]
Ok, I get it now！Thanks again for your kind help！
