### ISSUE TITLE
Warning:optimizer contains a parameter group with duplicate parameters

### ISSUE THREAD

**Issue by yuheyuan** [qinenergy/corda#13]
I follow you code,  and train a model. But it results may not meet the need.

I eval the model you share .
```txt
bash shells/eval_syn2city.sh
```
your share model. 
in syn2city :  19 classes : meanIout: 0.4771
I train the model:
in syn2city :  19 classes : meanIout:  only: 0.46.7

in the train. I find the warning, So I want to know  if it may cause the result drop.
```txt
/home/ailab/anaconda3/envs/yy_CORDA/lib/python3.7/site-packages/torch/optim/sgd.py:68: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(SGD, self).__init__(params, defaults)
D_init tensor(134.8489, device='cuda:0', grad_fn=<DivBackward0>) D tensor(134.5171, device='cuda:0', grad_fn=<DivBackward0>)
```

**Comment by qinenergy** [comment]
Hi, your achieved result (46.7/19*16=55.5 in 16 classes) is already slightly better than what we reported in the [paper](https://arxiv.org/pdf/2104.13613.pdf) 55.0 mIoU. 

As we mentioned in the ReadMe file Table, the paper's result(55.0) is based on 5 different runs. The provided model~(56.3) is our best run.
