### ISSUE TITLE
how to use DACS

### ISSUE THREAD

**Issue by yuheyuan** [qinenergy/corda#14]
In your paper use DACS as baseline.
However, DACS don't propose the SYNTHIA->CITYSCAPES trainning.
So, I want to ask you how you use trainning DACS.
I read you code. Should I need to delete all code which use depth in trainning. because I need to use DACS in SYNTHIA->CITYSCAPES to obtain data in my work 
![image](https://user-images.githubusercontent.com/39433014/222092727-69e8ac80-2a59-477a-867c-13683dedaad6.png)

Another question, When trainning finished, predictions direction will be created and some test pictures saved here.Where Can I find the code about it.

Maybe it's too long because this work is finished two years ago.You may forget some details.
I will be very appreciated if you reply me !

**Comment by qinenergy** [comment]
You can use directly the DACS code, a few lines need to be modified. 
Please see the discussion below in the DACS repo
https://github.com/vikolss/DACS/issues/4

The saving of the test image is in the evaluation code.    https://github.com/qinenergy/corda/blob/5896b77169ecef95f7c5f6ecc71a8f757291a505/evaluateUDA.py#L201.
