### ISSUE TITLE
Question about the pretrained parameters of backbone

### ISSUE THREAD

**Issue by super233** [qinenergy/corda#2]
Thanks for sharing the code, and it brings the amazing improvement for this filed.

I notice that you have used backbone with parameters pretrained on MSCOCO which is the same with [DACS](https://arxiv.org/abs/2007.08702), and have you tried backbone pretrained on ImageNet? If yes, could you please provide the corresponding results?

**Comment by qinenergy** [comment]
We had this question as well in the beginning for DACS. Thus we reran DACS for SYNTHIA2City with the ImageNet pretrained weight and the mIoU we got is 48.9. In comparison, we get 48.5 when we rerun DACS code with coco weight.  The reported number from DACS is 48.3, which is quite close to both numbers. This makes us believe that the coco/imagenet pretrained weights do not affect that much for the DACS framework. 

We thus later stick to the default DACS setting (coco) for further experiments.

**Comment by super233** [comment]
Ok I got it, thanks for your reply.

**Comment by qinenergy** [comment]
@super233 
Hi, I reran our CorDA training code with ImageNet-only pre-trained weight on the SYNTHIA2Cityscapes task. 

The mIoU peaked at 55.5(=46.7*19/16) and ended at 54.6. This is very close to our reported result 55.0 with the DACS's default pretrained weight. Hope this resolves your concern.
 
You can find the details [here](https://tensorboard.dev/experiment/awBpHaKQTXyvxJkA6LsogA/#scalars&_smoothingWeight=0).

**Comment by super233** [comment]
Thanks very much :-)
